# Generated by Django 3.1.5 on 2021-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registerbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbook',
            name='reason',
            field=models.CharField(default='', max_length=150),
        ),
    ]
